name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi!👋\n Welcome to the project! 💖\nThank you for opening this issue.\n\n**If anyone is interested to work on this issue, please comment below and you will be assigned with the task**.\n***Please make sure that you will link this issue to your Pull Request***."
        pr-message: "Hi!👋\nThank you for this Pull Request 💖.\nPlease adhere to our [`Code of Conduct`](https://github.com/SaptarshiSarkar12/Drifty/blob/master/CODE_OF_CONDUCT.md) and follow the [`Contributing Guidelines`](https://github.com/SaptarshiSarkar12/Drifty/blob/master/CONTRIBUTING.md).\nA maintainer will soon review this Pull Request."
